# Generated by Django 4.2.6 on 2023-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centercontrol", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_company", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("function", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admission", models.DateField(verbose_name="Data de Admissão")),
                ("dismissal", models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="centercontrol",
            name="cnpj",
            field=models.IntegerField(),
        ),
    ]
