# Generated by Django 4.2.6 on 2023-10-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centercontrol", "0002_worker_alter_centercontrol_cnpj"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_company", models.IntegerField()),
                ("cod_worker", models.IntegerField()),
                (
                    "date_vacation_start",
                    models.DateField(verbose_name="Data Inicio de Ferias"),
                ),
                (
                    "date_vacation_end",
                    models.DateField(verbose_name="Data Fim de Ferias"),
                ),
            ],
        ),
    ]
